FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://install.python-poetry.org | python3 -

# poetry PATH 설정
ENV PATH="/root/.local/bin:$PATH"

# Poetr 설정
RUN poetry config virtualenvs.create false

# 현재 디렉토리에서 바로 초기화 
RUN poetry init --no-interaction --name "my-app" --version:latest

# 의존성 설치
RUN poetry install

CMD ["bash"]

# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "18000", "--reload"]